### ISSUE TITLE
Error page in case reset wallet

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Mobile#1047] opened 2023-09-27 11:48 UTC
Describe the bug
Version test: v1.1.0(211)

To reproduce the bug 
Steps:
1. Go to Login screen 
2. Touch Forget account -> Erase all
3. Observe the displayed screen

Actual: Error page
Expect: Navigate to Welcome screen

**Comment by nguyenduythuc** [comment] 2023-10-03 02:36
@ThaoNguyen998 Can't reproduce this issue, i'll move this task to follow up

**Comment by nguyenduythuc** [comment] 2023-11-21 01:53
This issue has been open for a long time, i'll close this issue

**Closed by nguyenduythuc** 2023-11-21 01:53 UTC
